### PR TITLE
Optimize series.rolling.corr()

### PR DESCRIPTION
**Pull request by densmirn**
Result of current (multi-thread) implementation:

name | nthreads | type | size | median
-- | -- | -- | -- | --
Series.rolling.corr | 1 | Python | 400000 | 22.164
Series.rolling.corr | 1 | SDC | 400000 | 0.763
Series.rolling.corr | 4 | Python | 400000 | 22.605
Series.rolling.corr | 4 | SDC | 400000 | 0.604

`Python 1 / SDC 1 = 29.048`
`SDC 1 / SDC 4 = 1.263`
There is too weak scalability.

Just in case result of previous (non-optimal) implementation:

name | nthreads | type | size | median
-- | -- | -- | -- | --
Series.rolling.corr | 1 | Python | 400000 | 23.054
Series.rolling.corr | 1 | SDC | 400000 | 16.488

`Python 1 / SDC 1 = 1.398`
`SDC 1 / OPT_SDC 1 = 21.609`
`SDC 1 / OPT_SDC 4 = 27.298`

### CODE REVIEW

**Comment by AlexanderKalistratov** [comment]
pep

**Comment by densmirn** [comment]
Current performance:

name | nthreads | type | size | median
-- | -- | -- | -- | --
Series.rolling.corr | 1 | Python | 400000 | 22.483
Series.rolling.corr | 1 | SDC | 400000 | 0.344
Series.rolling.corr | 4 | SDC | 400000 | 0.172

`Python 1 / SDC 1 = 65.358`
`SDC 1 / SDC 4 = 2`

The latest patch additionally optimized the implementation.

**Comment by AlexanderKalistratov** [comment]
Any tests for the fix?

**Comment by densmirn** [comment]
> Any tests for the fix?

Added.

**Pull request merged**
