### PR TITLE
[WIP] Switch tests to new pipeline

### PR DESCRIPTION
**Pull request by Vyacheslav-Smirnov**
- Move all Azure configurations to use SDC_CONFIG_PIPELINE_SDC=0 (Windows, Linux, OSX)
 - Skip all failed tests for SDC_CONFIG_PIPELINE_SDC=0
 - Make configurations with SDC_CONFIG_PIPELINE_SDC=0 required for merge changes
 - Remain Travis to test SDC_CONFIG_PIPELINE_SDC=1 (Linux, Linux + MPI_NP = 1, Linux + coverage)
 - Smoke tests are disabled for builds with Numba 0.46 to focus on analyze of failed tests (sdc_pi_example.py fails for SDC_CONFIG_PIPELINE_SDC=0).

### CODE REVIEW

**Comment by Vyacheslav-Smirnov** [comment]
Going to skip failed tests using SDC_SKIP_FAILED_TESES variable as condition

**Comment by shssf** [comment]
> Going to skip failed tests using SDC_SKIP_FAILED_TESES variable as condition
Please, hold on. I will try to fix them. This PR will be merge if all tests passed.
Changes are ok - thank you.

**Comment by Vyacheslav-Smirnov** [comment]
It is decided to do the following:
 - Move all Azure configurations to use SDC_CONFIG_PIPELINE_SDC=0 (Windows, Linux, OSX)
 - Skip all failed tests for SDC_CONFIG_PIPELINE_SDC=0
 - Make configurations with SDC_CONFIG_PIPELINE_SDC=0 required for merge changes
 - Remain Travis to test SDC_CONFIG_PIPELINE_SDC=1 (Linux, Linux + MPI_NP = 1, Linux + coverage)

**Comment by Vyacheslav-Smirnov** [comment]
@PokhodenkoSA is working on skipping failed tests for SDC_CONFIG_PIPELINE_SDC=0
He will add these changes to the PR

**Pull request merged**
