### PR TITLE
Optimize series.rolling.kurt()

### PR DESCRIPTION
**Pull request by densmirn**
Result of current (multi-thread) implementation:

name | nthreads | type | size | median
-- | -- | -- | -- | --
Series.rolling.kurt | 1 | Python | 800000 | 4.329
Series.rolling.kurt | 1 | SDC | 800000 | 0.467
Series.rolling.kurt | 4 | Python | 800000 | 4.360
Series.rolling.kurt | 4 | SDC | 800000 | 0.248

`Python 1 / SDC 1 = 9.27`
`SDC 1 / SDC 4 = 1.883`

Just in case result of previous (non-optimal) implementation:

name | nthreads | type | size | median
-- | -- | -- | -- | --
Series.rolling.kurt | 1 | Python | 800000 | 4.567
Series.rolling.kurt | 1 | SDC | 800000 | 30.099

`Python 1 / SDC 1 = 0.158`
`SDC 1 / OPT_SDC 1 = 64.452`
`SDC 1 / OPT_SDC 4 = 121.367`

### CODE REVIEW

**Comment by AlexanderKalistratov** [comment]
Wow. That's great!

I'm a bit skeptical about using tuples. It makes numba to generate a lot of unnecessary code.
Haven't you tried to use list instead?

**Comment by densmirn** [comment]
> Wow. That's great!
> 
> I'm a bit skeptical about using tuples. It makes numba to generate a lot of unnecessary code.
> Haven't you tried to use list instead?

Let me a chance to try that.

**Comment by densmirn** [comment]
> > Wow. That's great!
> > I'm a bit skeptical about using tuples. It makes numba to generate a lot of unnecessary code.
> > Haven't you tried to use list instead?
> 
> Let me a chance to try that.

The similar code with using a list works ~70 times slower.

**Comment by AlexanderKalistratov** [comment]
@densmirn conflict

**Pull request merged**
