### PR TITLE
Scale Series.prod(skipna=True)

### PR DESCRIPTION
**Pull request by PokhodenkoSA**
image

### CODE REVIEW

**Comment by AlexanderKalistratov** [comment]
What's about perf test on numpy_like.prod? Are we going to do it?

**Comment by PokhodenkoSA** [comment]
> What's about perf test on numpy_like.prod? Are we going to do it?

Yes, I will do it. @1e-to made good framework for it.

**Comment by PokhodenkoSA** [comment]
> > What's about perf test on numpy_like.prod? Are we going to do it?
> 
> Yes, I will do it. @1e-to made good framework for it.

image

**Comment by AlexanderKalistratov** [comment]
@PokhodenkoSA conflict

**Comment by AlexanderKalistratov** [comment]
@PokhodenkoSA pep issue

**Pull request merged**
